### ISSUE TITLE
Verifying did identity with V3 does not seem to support custom RPC provider

### ISSUE THREAD

**Issue by jaffaskree** [Open-Attestation/oa-verify#162]
I am trying to verify documents using V3 and a custom RPC provider (having network id "cyan-imda").

1. _verificationBuilder_ takes an array of verifiers and some options. Thanks to these options, we can pass a custom ethers provider.

2. For each verifier, it calls verifier.verify(document, verifierOptions), so we can assume that our custom provider is passed to each verifier.

3. But looking at didIdentityProof verifier, we see that it calls verifyV3 without passing our custom provider.

4. Then verifyV3 calls verifySignature().

5. verifySignature immediately calls getPublicKey().

6. getPublicKey immediately calls resolve().

7. resolve tries to use the default resolver, which is configured with the default network and default RPC provider.

==> the error is thrown: "No conf for networkId: cyan-imda".
==> the error is propagated and finaly catched by the error wrapper withCodedErrorHandler.
==> verification fails.

**Comment by Nebulis** [comment]
Hi, thanks for the detailed report.

I guess you would expect a resolver to be built [that way](https://github.com/decentralized-identity/ethr-did-resolver#multi-network-configuration):
```
const providerConfig = {
  networks: [
    { name: "whatever", provider: ethersProvider }
  ]
}
```

We never tried to use ethers provider with `ethr-did-resolver` and the example mention only about web3. So I'm not sure whether ethers is fully supported but we can try.

However, provider is mainly meant for document store and token registry verification. For DID I think we should introduce a new resolver option maybe.

**Comment by hitesh-sm** [comment]
Please correct me if I am wrong Benoit @jaffaskree , I think the main problem we are facing here is that the provider is hardcoded to mainnet 
https://github.com/Open-Attestation/oa-verify/blob/ad06d88e963e95464c349af4f2c2dbb1bc07cb6d/src/did/resolver.ts#L8

This would mean that calls for resolving DID for any other network will fail. Can we instead pass the provider from options and only default to mainnet when there is no provider present in the options.

**Comment by jaffaskree** [comment]
@hitesh-sm Yes.

@Nebulis I didn't mean that the provider should necessary be ethers-like. Using ethers provider is not really the problem. 
What I had in mind is: it would be great to be able to pass our own config to the resolver in order to use custom network.

Currently, when calling verificationBuilder, the custom config seems to be dropped at the time you wrap the verify function inside withCodedErrorHandler.

In didIdentityProof.ts, line 110, verify receives 2 params: document and verifierOptions. Then, at line 113, it calls verifyV3 but pass only one arg: document.

At this point, it would be great if the verifierOptions were  passed to verifyV3.

Then, at line 95, verifyV3 calls verifySignature. At this point, it should also pass the verifierOptions. And so on, until the resolver is called with, this time, the custom options.

Another way to achieve this would be to allow us to directly pass a resolver to the verificationBuilder.

Something like:

```
interface EthrResolverConfig {
  networks: Array<{
    name: string;
    registry: string;
    rpcUrl: string;
  }>;
}

export function createResolvers(ethrResolverConfig: EthrResolverConfig): Resolver {
  return new Resolver({ ...ethrGetResolver(ethrResolverConfig), ...webGetResolver() });
}

export const verificationBuilder = <Document>(verifiers: Verifier<Document>[], resolver: Resolver) => (
  document: Document,
  promisesCallback?: PromiseCallback
): Promise<VerificationFragment[]> => {
  const promises: Promise<VerificationFragment>[] = verifiers.map((verifier) => {
    if (verifier.test(document, resolver)) {
      return verifier.verify(document, resolver);
    }
    return verifier.skip(document, resolver);
  });

  promisesCallback?.(promises);
  return Promise.all(promises);
};

// example:
const ethrResolverConfig: EthrResolverConfig = {
  networks: [
    {
      name: "cyan-imda",
      registry: "0xaE5a9b93Ac9....",
      rpcUrl: "https://cyan-imda.something....",
    },
  ],
};

const resolver = createResolvers(ethrResolverConfig);

const verifyBesu = verificationBuilder(
  [openAttestationHash, openAttestationDidIdentityProof, openAttestationDidSignedDocumentStatus],
  resolver
);
```

**Comment by Nebulis** [comment]
I'm fine with the resolver option.

 Looks like you have a good idea how do to it. Feel free to open a PR. Otherwise you will have to wait they one of us do it for you.

Let me know if you need some help.

**Comment by jaffaskree** [comment]
I opened a PR.
This is how I use it:
```

import { v3 } from '@govtechsg/open-attestation';
import {
  isValid,
  openAttestationDidIdentityProof,
  openAttestationDidSignedDocumentStatus,
  openAttestationHash,
  verificationBuilder,
  createResolver,
} from '@govtechsg/oa-verify';
import { ethers } from 'ethers';

const resolver = createResolver({
  networks: [{ name: 'my-network', rpcUrl: 'https://my-private-chain/besu', registry: '0xaE5a9b9...' }],
});

const verifyBesu = verificationBuilder<v3.SignedWrappedDocument<v3.OpenAttestationDocument>>(
  [openAttestationHash, openAttestationDidIdentityProof, openAttestationDidSignedDocumentStatus],
  {
    provider: new ethers.providers.JsonRpcProvider({ url: 'https://my-private-chain/besu' }),
    resolver,
  }
);

async function validate(document: v3.SignedWrappedDocument<v3.OpenAttestationDocument>): Promise<boolean> {
  const frags = await verifyBesu(document);
  const valid = isValid(frags);
  return valid;
}
```

**Comment by Nebulis** [comment]
Thanks for your contribution :smile_cat:

**Comment by jaffaskree** [comment]
My pleasure ;)
