### ISSUE TITLE
3 high severity vulnerabilities when installing oa-verify

### ISSUE THREAD

**Issue by hzingram** [Open-Attestation/oa-verify#164]
Huans-MBP:npm huan$ npm audit
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
fix available via `npm audit fix --force`
Will install @govtechsg/oa-verify@2.1.0, which is a breaking change
node_modules/@govtechsg/dnsprove/node_modules/axios
  @govtechsg/dnsprove  >=2.0.2
  Depends on vulnerable versions of axios
  node_modules/@govtechsg/dnsprove
    @govtechsg/oa-verify  >=3.0.0
    Depends on vulnerable versions of @govtechsg/dnsprove
    node_modules/@govtechsg/oa-verify

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --for

**Comment by cavacado** [comment]
stale closing
