### ISSUE TITLE
"Unable to query DNS" error

### ISSUE THREAD

**Issue by johnwen84** [Open-Attestation/oa-verify#222]
Hi, I'm testing my open attestation code that goes through the whole signing and verification process. And I'm running into problems verifying docs. Here is what I did,

- I created a wallet on etherium ropten, and registered document store using open-attestation CLI
- I used "https://sandbox.openattestation.com" to get a DNS TXT record
- I signed a document using the document store and the DNS TXT record, checked that the merkle root is issued to the document store
- I then tried to verify the document using the verify() function in @govtechsg/oa-verify. And I got a couple of errors. One of them is,
   - IDNS_QUERY_ERROR_GENERAL, Unable to query DNS

I noticed the same error from the open attestation CLI,
 - Use open-attestation dns txt-record create --address 0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5 --network-id 3
to get a DNS TXT record
 - Use open-attestation dns txt-record get --location to verify the DNS record
 - And I got the same "Unable to query DNS" error

I'm on the latest of everything,
@govtechsg/document-store 2.2.3
@govtechsg/oa-verify 7.9.0
@govtechsg/open-attestation 6.5.0
@govtechsg/open-attestation-cli 1.49.0

Please help me to solve this problem. Thanks in advance!

**Comment by cavacado** [comment]
could you please provide the temporary domain address generated by the open-attestation sandbox?

**Comment by johnwen84** [comment]
@cavacado Just registered one:
potential-olive-cow.sandbox.openattestation.com
It will expire by Sat Mar 19 2022 07:44:17 GMT-0400 (Eastern Daylight Time)
Thanks

**Comment by simboonlong** [comment]
i think he meant the particular address that responded with dns error, not a newly created one

a quick check on the newly created one with `npx @govtechsg/open-attestation-cli dns txt-record get --location potential-olive-cow.sandbox.openattestation.com` looks ok, shows:

<img width="772" alt="dns" src="https://user-images.githubusercontent.com/4774314/159001676-0068e22f-f4cf-430c-83eb-d480845ebf0a.png">

note that it will expire after 24 hours

**Comment by johnwen84** [comment]
Hi @simboonlong I used the open-attestation command, and this is what I got,
$ open-attestation dns txt-record get --location potential-olive-cow.sandbox.openattestation.com
You are falling back to oa-verify default configuration, which is not suitable for production environment. It is highly recommended that you configure and provide your own API key. Refer to https://github.com/Open-Attestation/oa-verify#provider
✖  error     Unable to query DNS

And I got the same error using your command,
$ npx @govtechsg/open-attestation-cli dns txt-record get --location potential-olive-cow.sandbox.openattestation.com
You are falling back to oa-verify default configuration, which is not suitable for production environment. It is highly recommended that you configure and provide your own API key. Refer to https://github.com/Open-Attestation/oa-verify#provider
✖  error     Unable to query DNS

I do realize that the domain expires in 20 hours, and I test before it does.

**Comment by simboonlong** [comment]
im guessing it choked at [here](https://github.com/Open-Attestation/dnsprove/blob/master/src/index.ts#L99), might be somehow your end/location can't access dns.google 🤔

are you able to access this url `https://dns.google/query?name=potential-olive-cow.sandbox.openattestation.com&rr_type=TXT`? it should return your txt record:

<img width="1121" alt="response" src="https://user-images.githubusercontent.com/4774314/159029315-be398278-ccb2-44e0-ad1a-117fbf5cd946.png">

**Comment by johnwen84** [comment]
Hmm you are right @simboonlong 
It looks like it might be a security setting. I'll see if I can do some adjustment there. But do you have any suggestions?
I had been using this to check on google dns and it works fine,
https://dns.google.com/resolve?name=potential-olive-cow.sandbox.openattestation.com&type=TXT
It returns this,
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"potential-olive-cow.sandbox.openattestation.com.","type":16}],"Answer":[{"name":"potential-olive-cow.sandbox.openattestation.com.","type":16,"TTL":60,"data":"openatts net=ethereum netId=3 addr=0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5"}],"Comment":"Response from 205.251.195.39."}

**Comment by johnwen84** [comment]
Hi @simboonlong, I got over the previous problem. It seems that my company might be blocking dns.google from my machine. So I deployed my code to AWS and was able to get a step further. But DNS is still failing, with a different error,
  {
    name: 'OpenAttestationDnsTxtIdentityProof',
    type: 'ISSUER_IDENTITY',
    data: [ [Object] ],
    reason: {
      message: 'Matching DNS record not found for 0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5',
      code: 4,
      codeString: 'MATCHING_RECORD_NOT_FOUND'
    },
    status: 'INVALID'
  }
The DNS that's generated is horrible-aquamarine-goldfish.sandbox.openattestation.com.
From AWS terminal I can curl https://dns.google/query?name=horrible-aquamarine-goldfish.sandbox.openattestation.com&rr_type=TXT
And when I used https://dns.google.com/resolve?name=horrible-aquamarine-goldfish.sandbox.openattestation.com&type=TXT, I got a result that looks correct,
{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "horrible-aquamarine-goldfish.sandbox.openattestation.com.",
      "type": 16
    }
  ],
  "Answer": [
    {
      "name": "horrible-aquamarine-goldfish.sandbox.openattestation.com.",
      "type": 16,
      "TTL": 60,
      "data": "openatts net=ethereum netId=3 addr=0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5"
    }
  ],
  "Comment": "Response from 205.251.195.39."
}

**Comment by johnwen84** [comment]
BTW if I run open-attestation dns txt-record get --location horrible-aquamarine-goldfish.sandbox.openattestation.com on the AWS terminal, I got a correct result,
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/25614319/160261421-cae33adf-dfb9-49f7-80a9-802a3c29fd78.png">

**Comment by simboonlong** [comment]
can we see the document you are trying to issue?

make sure:
1. `export OA_PRIVATE_KEY=<your wallet private key>` <- this wallet **MUST** be the same one that you used to deploy your document store (0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5).
2. your document `issuers[0].documentStore` is `0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5`
3. your document `issuers[0].identityProof.location` is the generated temporary dns.
4. wrap your document to get merkle root hash.
5. `open-attestation document-store issue --address 0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5 --hash <your document hash> --network ropsten`

**Comment by johnwen84** [comment]
@simboonlong I'm trying to do everything programmatically, instead of using the CLI. From what you described, it seems that the only thing I'm missing is that I didn't set the OA_PRIVATE_KEY. Is that for the CLI, or do I need to set it for my code to run?
Here is the wrapped document:
---------------
{
  "version": "https://schema.openattestation.com/2.0/schema.json",
  "data": {
    "firstName": "02dde111-918d-47df-bd50-9e5d55e9bc57:string:Alice",
    "lastName": "5e5b3d74-4198-4f56-a0e2-5531baa1af0a:string:Smith",
    "$template": {
      "name": "53710230-040a-40a9-b3e9-50f578618ebc:string:main",
      "type": "6f0c09f1-abb8-48c2-99ca-6eeecb5ef3dd:string:EMBEDDED_RENDERER",
      "url": "c3092241-145a-4f32-8dba-0f93fcb2ac83:string:https://tutorial-renderer.openattestation.com"
    },
    "issuers": [
      {
        "name": "6a1da6c5-2781-4d72-bd56-2ebed8e54a4b:string:Demo Issuer",
        "documentStore": "37833ed7-c2ef-4300-a82d-7b376334612c:string:0xFdda6f76735BE5860d1d9Bd8C0F79a09826558C5",
        "identityProof": {
          "type": "fec7edf6-2170-4a71-be90-e20a62887e0f:string:DNS-TXT",
          "location": "ea9a0f62-e770-4d8b-a90b-41645abd3984:string:horrible-aquamarine-goldfish.sandbox.openattestation.com"
        }
      }
    ],
    "recipient": {
      "name": "961ddc8d-2b46-4b6a-9c36-7b7d54f73088:string:Demo Recipient"
    }
  },
  "signature": {
    "type": "SHA3MerkleProof",
    "targetHash": "143aab0572bee621cc2457f7249a1d574f26bb31ac6e7989f1035403d444de6f",
    "proof": [],
    "merkleRoot": "143aab0572bee621cc2457f7249a1d574f26bb31ac6e7989f1035403d444de6f"
  }
}

**Comment by cavacado** [comment]
if you're trying to verify programmatically, is it possible for us to take a look at your repository?
You might have configured certain things wrongly

**Comment by johnwen84** [comment]
@cavacado @simboonlong Here is my repository,
https://github.com/johnwen84/small-oa
Thanks

**Comment by cavacado** [comment]
https://github.com/johnwen84/small-oa/blob/49a1da43ce957768ca2843150c7816d03b352e9d/src/oa.js#L174

the `verify` function that you are using is using the default verification builder options, (ie, its using the homestead (main) network instead of ropsten network)

in order to configure it properly, please read up on how to construct the verifiers.
https://github.com/Open-Attestation/oa-verify#switching-network

**Comment by johnwen84** [comment]
@cavacado Ah that makes a lot of sense. Thanks you for catching that. I'll look into it over the weekend and report back to you.

**Comment by johnwen84** [comment]
@cavacado @simboonlong it all works now. Thanks for all your help!
I hope there can be more error messages, though. For instance 
- if I change an issued document and try to verify, I don't get any specific error message
- if I issue a document with a wrong DNS, I don't get any specific error message when I try to verify. 
- if I wrap a doc with a wrong document store address, I don't get and specific error message when I try to verify
The verification fails properly in all cases, but no specific error message to report to the user. All fragments returned from the verify() call are in status SKIPPED or VALID.

**Comment by cavacado** [comment]
- if I change an issued document and try to verify, I don't get any specific error message

Could I clarify this statement abit more? Are you trying to say that if I modify the issued document (ie changing a field in the wrapped document, like name from John to Joe, effectively tampering it?), then you dont get any specific error message when you verify?

- if I issue a document with a wrong DNS, I don't get any specific error message when I try to verify.
- if I wrap a doc with a wrong document store address, I don't get and specific error message when I try to verify

For these cases, how would the independent modules know about whether the information supplied is wrong? In the first place what is a wrong DNS or wrong document store address? To me, this seems like a integrator's specific problem as an integrator would have the sufficient knowledge to understand what is "right" or "wrong" and thereby handle the exceptions accordingly, at this level (library level) we try not to concern ourselves with these issues.
I hope this helps.

**Comment by johnwen84** [comment]
@cavacado 

1. yes if I change say the last name of the recipient, and try to verify, it fails but I don't get any specific message.
2. I used a DNS like aaa. It wraps and issues the doc ok. When I try to verify, It fails but no message. I'd expect a "Unable to query DNS" message like I had when dns.google was blocked on my machine
3. If I use a wrong doc store address, I can't issue it, but I can wrap. And if I try to verify the wrapped doc it fails, but no message. I'd expect a message like "Invalid document store".

**Comment by cavacado** [comment]
did you inspect the `fragments` object returned by the verifier manager? That should give the desired "error" (more like status) messages you need.
The point to note is that the verifier manager is a run-to-completion construct, it doesnt fail immediately once it encounters an error.

on point 3 about allowing wrapping invalid doc store addresses, we have a schema check, but its a loose schema check, whereby as long as the doc-store address is a string we accept it. 

Feel free to open any improvement PRs if you feel that what we have currently is not good enough.

**Comment by johnwen84** [comment]
@cavacado yes I loop through the fragments, check the status and if it's ERROR I return the message of it to the user. But in those cases I listed, status of all fragments are VALID or SKIPPED.

**Comment by cavacado** [comment]
okay, could you provide
1) the log of the `fragments` object that has all `VALID` or `SKIPPED`
2) the tampered document and untampered document.

we will take a look at it if time permits.

**Comment by johnwen84** [comment]
@cavacado @simboonlong I'm closing this issue. OA is giving correct error message. I just needed to check both status "ERROR" and "INVALID'.
Thanks for all your help. I'm all good now.
