### ISSUE TITLE
Verification Configuration for DID signed document through OCSP

### ISSUE THREAD

**Issue by enjoykcc456** [Open-Attestation/oa-verify#237]
Hi, 

I have been working on DID signed documents through an Online Certificate Status Protocol (OCSP) responder (https://www.openattestation.com/blog/revocation-ocsp-responder/). While doing verification on the signed document using oa-verify library, I am currently using the configuration as follow:

`const provider = utils.generateProvider();`
`const verify = verificationBuilder(openAttestationVerifiers, { provider });`

However, with this configs, I realised there are additional calls to infura whenever a verification is done. Hence, would like to check what would be the suggestion provider and resolver configuration for verification on DID signed document with OCSP. Thanks!

**Comment by HJunyuan** [comment]
Hi @enjoykcc456,

Yes, having calls to Infura when performing verification is normal as the verification process involves resolving the DID that was used to sign the document.

In your example, you did not specify a specific resolver to use, so the library makes use of the default resolver from Infura. You may refer to the docs on how to specify your own resolver here: https://github.com/Open-Attestation/oa-verify#specify-resolver

Or you can refer to this quick example:
```typescript
import { providers } from "ethers";
import { Resolver } from "did-resolver";
import { getResolver } from "ethr-did-resolver";
import { verificationBuilder, openAttestationVerifiers } from "@govtechsg/oa-verify";

const NETWORK_NAME = "goerli";

const provider = new providers.AlchemyProvider(NETWORK_NAME, ALCHEMY_API_KEY);
const resolver = new Resolver(getResolver({ name: "goerli", provider }));

const verify = verificationBuilder(openAttestationVerifiers, {
  provider,
  resolver,
  network: NETWORK_NAME,
});

```

I will proceed to close this issue for now as it seems more like a discussion. Feel free to create a new discussion here if needed: https://github.com/Open-Attestation/open-attestation/discussions
