### ISSUE TITLE
OCSP responder for v3 documents

### ISSUE THREAD

**Issue by morgatron** [Open-Attestation/oa-verify#243]
The OCSP responder looks great for DID-signed documents, especially those for v3. However it seems that v3 documents aren't currently supported:
```
      case v3.RevocationType.OcspResponder:
        throw new Error("Ocsp revocation type not yet supported for v3");
```
(from `didSignedDocumentStatus.ts`)
This seems pretty straightforward to add however, using the v2 code as a guide.

 Are there any plans to add this?

**Comment by HJunyuan** [comment]
Hi @morgatron, thanks for the suggestion! We'll add this into our backlog and keep you updated here when it gets implemented.

**Comment by morgatron** [comment]
Thanks @HJunyuan !
I'm guessing you can't give us a time estimate? ;)

**Comment by morgatron** [comment]
To be clear,  it's looking like this will be important for our customer. We'll be needing the feature in the next couple of months... 

any clarity you can provide would be fantastic.

**Comment by morgatron** [comment]
I could be wrong, but it looks as simple as replacing

```js
  case v3.RevocationType.OcspResponder:
    throw new Error("Ocsp revocation type not yet supported for v3");
```

with
```js      
  case v3.RevocationType.OcspResponder:
    if (typeof location === "string") {
      return isRevokedByOcspResponder2({
        merkleRoot,
        targetHash,
        proofs,
        location,
      })
    }
```

I can raise a PR if desired, but I'm not sure I understand how tests work for this currently so I'm not sure I can update them.

Let me know!

**Comment by HJunyuan** [comment]
Yes you are right! We'll just need to focus on creating the tests and it should be done. Will get started on this around this or next week or when the new sprint starts.

**Comment by morgatron** [comment]
Great!!
