### ISSUE TITLE
"Uncaught ReferenceError: process is not defined" when using oa-verify library

### ISSUE THREAD

**Issue by joeltancej** [Open-Attestation/oa-verify#257]
Hi, newbie here. I'm using the @govtechsg/oa-verify library to verify a wrapped document in my React app as such:

```
const fragments = await verify(wrappedDocument as any);
console.log(isValid(fragments));
```

However, when I run the app, I get this error:
```
config.js:1 Uncaught ReferenceError: process is not defined
    at config.js:1:29
```
![image](https://github.com/Open-Attestation/oa-verify/assets/64303711/7d52e31c-cd50-413a-b468-691ffe60ca0e)

What can I do to fix this issue? I've tried a couple of methods suggested on the internet and they don't seem to work. Thanks!

**Comment by simboonlong** [comment]
it depends on your setup and how you want to handle your env variables. u can do a “replace” of env variables on webpack config level during build time.

in anyways we encourage you to sign up for your own infura key if u need one, the one we provide is free tier. what i suggest is:

- try remove the process.env and hardcode that bb46… first. does that work?
    - if it work, sign up for your own key instead. do take care on how you want to expose this key.
    - if it doesn’t work, some parts of your code might be incorrect. providing a repo will be great.

**Comment by joeltancej** [comment]
@simboonlong thanks for the reply!
To remove the process.env and hardcode the API key, would I have to edit the node modules directly? It seems that direct edits to the node modules don't get reflected when I run the app, and I may have to find another way to do this.

**Comment by joeltancej** [comment]
> it depends on your setup and how you want to handle your env variables. u can do a “replace” of env variables on webpack config level during build time.
> 
> in anyways we encourage you to sign up for your own infura key if u need one, the one we provide is free tier. what i suggest is:
> 
> * try remove the process.env and hardcode that bb46… first. does that work?
>   
>   * if it work, sign up for your own key instead. do take care on how you want to expose this key.
>   * if it doesn’t work, some parts of your code might be incorrect. providing a repo will be great.

@simboonlong thanks for the reply!
To remove the process.env and hardcode the API key, would I have to edit the node modules directly? It seems that direct edits to the node modules don't get reflected when I run the app, and I may have to find another way to do this.

**Comment by HJunyuan** [comment]
@joeltancej This seems like an issue related to your React project setup (i.e. not a `oa-verify` library issue).

In any case, could you double-check on your Webpack configuration (if any)? A quick Google search revealed [this plugin](https://bobbyhadz.com/blog/react-referenceerror-process-not-defined#if-you-have-a-webpack-configuration) that you can use for environment variables to load accordingly.

If that still does not work, we would recommend that you create a new/clean React application using a framework like [Next.js](https://nextjs.org/). Then try to import the `oa-verify` library and see if it works.

**Comment by simboonlong** [comment]
yup @HJunyuan is right. closing as not related to oa-verify.

**Comment by joeltancej** [comment]
@HJunyuan @simboonlong  Thanks for the response!
