### ISSUE TITLE
Format Of Issuer Name

### ISSUE THREAD

**Issue by wmclaxton** [Open-Attestation/oa-verify#258]
I would like to know how to populate the issuers block in the JSON certificate data so that both the issuer name and the issuer domain appear in the verification service, as shown by this example image.

![issued_by_ntu](https://github.com/Open-Attestation/oa-verify/assets/21061332/54429ed3-3f91-4972-9c94-3e331cb13116)

**Comment by HJunyuan** [comment]
Hi @wmclaxton, this block (showcasing both the issuer name and domain) will only appear for [issuers already in the OpenCerts registry or an issuer with a trusted TLD](https://github.com/OpenCerts/opencerts-website/blob/8f7d4135402c931df3cb209a249365122db6f414/src/components/CertificateVerifyBlock/CertificateVerifyBlock.tsx#L77-L84).

However, please note that the OpenCerts registry has already been dissolved and we will not be adding any new institutions into it.

Moving forward, as long as the issuer TLD is trusted (e.g. `*.edu.sg`, this block should automatically appear.

**Comment by wmclaxton** [comment]
So am I correct to say that for https://geainstitute.edu.sg/ the verification page would show 'GEA Institute geainstitute.edu.sg'?  Am I also correct that a private training provide such as Hongbao Media would only be shown as 'hongbaomedia.com' and not displaying the company name?

Also, nextid.com should be in that registry, but we only see the domain and not name when doing verification.

**Comment by HJunyuan** [comment]
> So am I correct to say that for https://geainstitute.edu.sg/ the verification page would show 'GEA Institute geainstitute.edu.sg'? Am I also correct that a private training provider such as Hongbao Media would only be shown as 'hongbaomedia.com' and not displaying the company name?

Yes, that is my understanding as well.

> Also, nextid.com should be in that registry, but we only see the domain and not name when doing verification.

I do not see nextid.com listed in the registry. Please ensure you are issuing the document to the same document store that was previously added to the registry.

**Comment by wmclaxton** [comment]
I understand that GovTech decided against listing organisation names for those not already white listed in order to limit the potential for name falsification.  I am therefore closing the issue.
